spring:
  autoconfigure:
    exclude:
      # Disable Eureka autoconfigurations
      - org.springframework.cloud.netflix.eureka.config.EurekaDiscoveryClientConfigServiceAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      # Disable Consul autoconfigurations
      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
      - org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration
      - org.springframework.cloud.consul.ConsulAutoConfiguration
      - org.springframework.cloud.consul.discovery.ConsulCatalogWatchAutoConfiguration
      # Disable Kubernetes autoconfigurations
      - org.springframework.cloud.kubernetes.KubernetesAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatchAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.reactive.KubernetesReactiveDiscoveryClientAutoConfiguration
      - org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration
  ## Uncomment following lines to add a service to discover
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            service1:
#              - uri: http://localhost:8080
